"""Content-led product site. No runtime framework, network fonts or analytics."""
from pathlib import Path
import html,json
ROOT=Path(__file__).resolve().parents[1]
BASE='https://gonisulaimann.github.io/'
REPO='https://github.com/gonisulaimann/Prepare'
PRODUCT=json.loads((ROOT/'product.json').read_text())
esc=html.escape

def link(href,label,cls=''):
    return f'<a class="{cls}" href="{href}">{label}</a>'
def section(title,text):return f'<section class="prose"><h2>{title}</h2>{text}</section>'
def cards(items):return '<div class="cards">'+''.join(f'<article><span class="index">{i:02}</span><h2>{t}</h2><p>{v}</p></article>' for i,(t,v) in enumerate(items,1))+'</div>'
def shell(title,deck,body,path='',eyebrow='Prepare / Field guide'):
    url=BASE+path
    plain=title.replace('<br>',' ')
    schema=json.dumps({'@context':'https://schema.org','@type':'SoftwareApplication','name':'Prepare','applicationCategory':'UtilitiesApplication','operatingSystem':'Windows, Linux, macOS; browser workspace','url':BASE,'license':REPO+'/blob/main/LICENSE'})
    nav=''.join(link('/'+p+'/',label) for p,label in [('workflows','Workflows'),('download','Download'),('documentation','Documentation')])
    footer=''.join(link('/'+p+'/',label) for p,label in [('privacy','Privacy'),('security','Security'),('accessibility','Accessibility'),('licensing','License'),('community','Community'),('about','About'),('contact','Contact')])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(plain)} — Prepare</title><meta name="description" content="{esc(deck,quote=True)}"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title,quote=True)} — Prepare"><meta property="og:description" content="{esc(deck,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}assets/social-preview.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(plain,quote=True)} — Prepare"><meta name="twitter:description" content="{esc(deck,quote=True)}"><meta name="twitter:image" content="{BASE}assets/social-preview.png"><script type="application/ld+json">{schema}</script><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Prepare home"><span class="brand-mark" aria-hidden="true">P</span>Prepare<span class="brand-note">LOCAL BY DESIGN</span></a><nav aria-label="Primary">{nav}{link('/workspace/','Open workspace ↗','nav-action')}</nav></header><main id="main" tabindex="-1"><div class="page-intro"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="deck">{deck}</p></div>{body}</main><footer class="site-footer"><div><a class="brand" href="/">Prepare</a><p>A copy. A check. A record.<br>No account. No document uploads.</p></div><nav aria-label="Footer">{footer}{link(REPO,'GitHub ↗')}{link('/terms/','Terms')}</nav><p class="fine">Current project-owned source: Apache-2.0. Dependencies retain their licenses.<br>Historical downloads through 0.8 retain Hippocratic 3.0. No license change is implied for old artifacts.</p></footer></body></html>'''

pages={}
def add(slug,title,deck,body):pages[slug]=(title,deck,body)

home='''<div class="hero-actions"><a class="button" href="/workspace/">Try the local workspace <span aria-hidden="true">↗</span></a><a class="text-link" href="/download/">Choose a download →</a><span class="fine">PDF workflow · no install · processing on your device</span></div>
<section class="proof-board" aria-labelledby="proof-title"><div class="proof-heading"><p class="eyebrow">THE PREPARATION LOOP</p><h2 id="proof-title">The file is not the finish line.</h2><p>You need the right copy, for the right requirements,<br>with a way to check it afterwards.</p></div><ol class="loop"><li><span>01</span><strong>Import</strong><p>Keep your original.</p></li><li><span>02</span><strong>Understand</strong><p>Inspect what is there.</p></li><li><span>03</span><strong>Prepare</strong><p>Make a separate copy.</p></li><li><span>04</span><strong>Validate</strong><p>Check your requirements.</p></li><li><span>05</span><strong>Verify</strong><p>Review the result.</p></li><li><span>06</span><strong>Export</strong><p>Keep the copy and receipt.</p></li></ol><p class="board-note">Real workflow, not an animated mockup. <a href="/workspace/">Open it and use a synthetic sample →</a></p></section>
<div class="section-heading"><p class="eyebrow">BUILT AROUND THE HANDOFF</p><h2>Less “convert anything.”<br>More “ready for this.”</h2></div>'''+cards([
('Know the requirements','Set your own byte limit and page limit. Save a reusable profile. A size limit is a ceiling—not a promise that compression can reach it.'),
('Keep evidence with the copy','A receipt binds the prepared bytes to a SHA-256 fingerprint. Recheck a saved copy later. Receipts are editable and unsigned, not authenticity certificates.'),
('Make unknowns visible','Mechanical checks do not establish legibility, accessibility, security or portal acceptance. Prepare keeps that distinction visible instead of inventing a green score.')])+'''<section class="split-feature"><div><p class="eyebrow">ONE PRODUCT. DIFFERENT SURFACES.</p><h2>Use the smallest tool<br>that does the job.</h2></div><div><p>The browser workspace handles focused PDF preparation. The desktop suite adds images, text-first documents, PDF rendering and optional local OCR/media engines. The extension keeps the workspace next to your application tab.</p><a href="/platforms/">Compare actual capabilities →</a></div></section><section class="prose"><h2>Existing users are not left behind.</h2><p>Small, older tools remain available with their original scope and license: <a href="https://github.com/gonisulaimann/Prepare/releases/download/v0.5.0/Prepare-0.5.0-arm64.zip">stable Apple Silicon image utility</a> and <a href="https://github.com/gonisulaimann/Prepare/releases/download/v0.5.0/Prepare-0.5.0-portable.zip">stable portable image bundle</a>. They are not substitutes for the new suite.</p></section>'''
(ROOT/'index.html').write_text(shell('Make the right copy.<br>Know what changed.','Local document preparation, built around your requirements—not a list of file extensions.',home,eyebrow='PREPARE / LOCAL DOCUMENT WORKSPACE'))

add('features','Evidence, not guesswork.','Choose a workflow by the result you need. Each surface has explicit boundaries.',cards([
('Requirements','Personal byte, page, format, dimension, orientation and filename profiles. Desktop and browser adapters share a declarative schema; format support differs.'),('PDF preparation','Browser: merge, reorder, remove, rotate and extract pages, with undo/redo. Desktop: previews, optimize, rasterize, encrypt/decrypt, fill and annotate.'),('Broader local preparation','Desktop image conversion, text-first document conversion, optional Tesseract OCR and FFmpeg media conversion. Arbitrary files can be ZIP/GZ packaged—not universally converted.'),('Verification receipts','New workspace generation records output bytes and a hash. Desktop gates failed requirements before publication. Browser requires acknowledgment of manual review before download.')])+section('Choose the right scope','<p><a href="/supported-formats/">Supported formats</a> · <a href="/readiness/">What checks prove</a> · <a href="/platforms/">Platform qualification</a></p>'))
add('workflows','Start with the requirement.','Three useful paths—not a hundred disconnected tools.',cards([
('Prepare a PDF for an application','Set the actual portal limits yourself. Import PDFs, order the pages, create a copy, inspect the checks and open the saved file in a PDF reader. Never assume a named institution is certified.'),('Create a reusable preparation rule','Load a personal JSON profile for recurring work. Keep the same mechanical requirements across the browser and desktop, while respecting each adapter’s supported formats.'),('Check a copy after the handoff','Keep a receipt separately. Select it and a later copy to compare SHA-256 and byte count. A mismatch means different bytes; a match does not establish authorship or safety.')])+section('Try the complete path','<p><a class="button" href="/workspace/">Open the real local workspace</a></p><p>The sample is synthetic. Your files are selected explicitly and processed locally.</p>'))
add('readiness','A check is not a promise.','Readiness is bounded evidence against requirements you supply.',section('Three outcomes','<dl><dt>Pass</dt><dd>The observed fact satisfies the named rule.</dd><dt>Fail</dt><dd>The observed fact violates the rule. Adjust the transformation or requirement.</dd><dt>Unknown / needs review</dt><dd>The adapter cannot establish the fact. Unknown is never a pass.</dd></dl>')+section('What remains yours to review','<p>Legibility, every page’s appearance, accessibility, content correctness, intended recipients, institutional acceptance and any signature workflow. Parsing is not complete PDF conformance validation. No health score hides those gaps.</p>')+section('Receipts are not certificates','<p>A receipt records output fingerprint, mechanical evidence and requirements. It is editable, unsigned and can expose document fingerprints and requirements. Keep it private where appropriate. The verification tool compares bytes; it does not authenticate the receipt.</p>'))
add('profiles','Requirements you can reuse.','A small declarative JSON file, not code running on your computer.',section('Example: a personal PDF ceiling','<pre><code>{\n  "version": 1,\n  "id": "my-application",\n  "constraints": {\n    "formats": ["pdf"],\n    "bytes": {"max": 2000000},\n    "pageCount": {"min": 1, "max": 5}\n  }\n}</code></pre><p>This is an example, not an official portal profile. Two million bytes means decimal 2 MB. Verify current requirements at the destination.</p>')+section('Supported rule vocabulary','<p>Byte ranges, page counts, PNG/JPEG/PDF formats, dimensions in px or pt, orientation and filename rules. Units must match observed evidence. No executable actions, network sources or institutional certification are embedded.</p><p><a href="/workspace/">Load a profile in the workspace →</a></p>'))
add('supported-formats','Explicit formats.<br>Explicit trade-offs.','Packaging a file is not converting its meaning. Check the actual supported paths.',section('Browser workspace and extension','<p>PDF input/output: merge, page order, rotation and extraction. 100 pages, 20 MB per input, 50 MB combined input; no encrypted files, rendering, OCR, forms editing or universal PDF compatibility. Outputs are rewritten copies, not signature-preserving edits.</p>')+section('Desktop suite','<p>Images: PNG, JPEG, WebP, TIFF, BMP, GIF, ICO, PPM and image-to-PDF paths where offered by the format-aware selector. Text/document adapters include plain text, Markdown, HTML, CSV/TSV, JSON, DOCX, PPTX, XLSX, ODT and EPUB extraction with text-first outputs. Office formatting, equations and arbitrary layout are not preserved.</p><p>PDF: PDF, PNG/JPEG page rendering, text extraction, OCR PDF/text with local Tesseract. Media: supported audio/video through local FFmpeg. Any ordinary file up to the size bound: ZIP or GZ packaging.</p><p><a href="/documentation/DESKTOP-SUITE.html">Exact suite matrix and bounds →</a></p>'))
add('platforms','Cross-platform.<br>Not identical-platform.','A clear distinction between tested native packages, browser workflows and experiments.',cards([
('Desktop','Native Python/Tk suite builds for Windows x64, Linux x64, macOS Apple Silicon and Intel. Builds must pass platform CI and frozen-worker tests before release. Unsigned/not notarized; no claim for every OS version.'),('Web','A local-processing PDF workspace and retained portable image tool. A website running on a phone is not an iOS app.'),('Browser extension','MV3 Chromium/Edge package and Firefox adapter. Installed-extension workflows tested locally. Store listings are not published. Safari is blocked by missing converter/signing/distribution prerequisites.'),('Mobile','Android image-to-PDF APK is an unsigned experimental 0.5 artifact, not desktop-suite parity. No native iOS or iPadOS application is published.')])+section('Details','<p><a href="/desktop/">Desktop</a> · <a href="/extension/">Extension</a> · <a href="/web/">Web</a> · <a href="/mobile/">Mobile</a> · <a href="/cli/">CLI</a></p>'))
add('desktop','The broader local workbench.','For documents, images and PDF work that needs installed engines.',section('Prepare without losing the original','<p>The suite snapshots input for processing, stages a new output and refuses to replace an existing destination. Work runs in a separate cancellable process. PDF previews identify their source; local Tesseract and FFmpeg are optional, separately installed engines.</p><p>The 0.9 workspace generation adds requirement gates before publication, receipts and a CLI over the same worker. These are beta workflows, not a sandbox guarantee.</p><p><a class="button" href="/download/">Desktop downloads</a></p>')+section('Installation boundaries','<p>Extract the complete directory; do not move just the executable. macOS binaries are not notarized. Windows binaries are unsigned. Organizational policies may prevent execution. Do not disable operating-system security to run Prepare.</p>'))
add('extension','The preparation tab<br>beside your application tab.','A real local PDF workspace. No access to the page you are visiting.',section('Deliberately narrow permissions','<p>No host permissions, content scripts, upload interception, native messaging or remote code. Clicking the extension opens its own workspace. You choose local PDFs explicitly; the extension cannot read arbitrary downloads or form fields.</p>')+section('Published packages; not store listings','<p>The 0.9 beta extension packages are available on GitHub with checksums. See <a href="https://github.com/gonisulaimann/Prepare/tree/main/extension">installation instructions and source</a>. Chromium and Edge use unpacked developer mode. Firefox uses temporary add-on installation in about:debugging, removed on browser restart. Neither is a store publication or a normal permanent Firefox install.</p><p>Chrome Web Store, Edge Add-ons and AMO need authenticated owner access and applicable developer agreements/review. Safari additionally needs Apple tooling, signing and distribution qualification. No store listing is claimed.</p><p><a href="/download/">Published desktop and extension packages →</a> · <a href="/privacy/">Privacy disclosure</a> · <a href="/contact/">Support</a></p>'))
add('web','Open a file.<br>Keep it on your device.','The workspace executes locally in the browser, with no account or document upload.',section('Two honest network boundaries','<p>Opening this hosted page downloads its static assets from GitHub Pages. GitHub may receive normal hosting request metadata. Selected document contents are not uploaded by Prepare. Download the offline bundle if you need to work without contacting the website at all.</p><p><a class="button" href="/workspace/">Open workspace</a></p>')+section('The browser is not the desktop suite','<p>PDF page preparation and receipts are available here. Desktop rendering, OCR, passwords, document conversions and FFmpeg integrations are not silently implied.</p>'))
add('mobile','Mobile, without<br>pretend parity.','An experimental Android utility remains available. Native iOS and iPadOS applications are not published.',section('Android experiment','<p>The 0.5 image-to-PDF APK targets Android 9+ and requests no manifest permissions, including INTERNET. It remains unsigned and experimental. Do not interpret that artifact as the desktop workspace on Android.</p><p><a href="https://github.com/gonisulaimann/Prepare/releases/tag/v0.5.0-android-experimental.1">Historical Android release →</a></p>')+section('iPhone and iPad','<p>Web pages may work in your browser, subject to browser capabilities and memory. That is not a native app qualification. No App Store listing or native iOS package is claimed.</p>'))
add('cli','The same worker.<br>A repeatable command.','Automate supported preparation and byte verification without a GUI.',section('Desktop CLI, 0.9 generation','<pre><code>Prepare-Desktop formats input.png\nPrepare-Desktop prepare input.png --target pdf \\\n  --output prepared.pdf --max-bytes 2000000\nPrepare-Desktop prepare input.png --target pdf \\\n  --output another-copy.pdf --profile requirements.json\nPrepare-Desktop verify prepared.pdf --receipt receipt.json</code></pre><p>The preparation response contains the receipt object; save that object as JSON to verify later. Source invocation: <code>python desktop/launch.py</code> followed by the same arguments, with desktop requirements installed. Errors use exit 1; a fingerprint mismatch uses exit 2.</p>')+section('No accidental overwrites','<p>Use a fresh destination. Failed mechanical requirements block publication; unknown checks remain unknown. Interruptions may leave a copy completed immediately before cancellation.</p>'))
add('getting-started','Your first prepared copy.','No account. No onboarding wizard. Start with the file and the actual requirement.',section('Browser or extension','<ol><li>Open the workspace. Try the synthetic sample first if useful.</li><li>Choose your PDFs and set actual byte/page limits.</li><li>Order, remove or rotate pages. Undo/redo stays local to the open session.</li><li>Create the copy and read every failed or unknown check.</li><li>Save a new file and optional receipt. Open the saved PDF in a reader and inspect every page.</li></ol>')+section('Desktop','<ol><li>Choose a qualified beta package and extract the entire folder.</li><li>Open the app; select a file and an offered output format.</li><li>Set personal requirements if applicable. Choose a new destination.</li><li>Review output and save the optional receipt.</li></ol><p>For OCR/media, install the optional local engine yourself. <a href="/requirements/">Requirements and limitations →</a></p>'))
add('requirements','Know the boundaries<br>before you install.','No account or cloud conversion dependency. Some workflows need optional local software.',section('Desktop','<p>Supported release architectures are Windows x64, Linux x64 and macOS ARM64/x64. Qualification evidence names the CI hosts; it is not a promise of every historical OS version. Keep the extracted runtime together. Use a local filesystem with hard-link support for exclusive output publication.</p><p>Optional engines: Tesseract for OCR; FFmpeg for media. They are not bundled or downloaded automatically. Desktop inputs/outputs are bounded at 100 MiB, with tighter page/render/parser limits.</p>')+section('Browser','<p>JavaScript and Web Workers required. Files stay in memory while the workspace is open. Reloading loses unsaved work. Large documents may exceed device limits even within the published input bounds.</p>'))
add('privacy','Privacy is a boundary,<br>not a badge.','No document uploads, accounts, analytics or telemetry in Prepare’s processing workflow.',section('Local processing','<p>Desktop conversion is local. The extension has no host permissions and its CSP forbids network connections. The web workspace processes explicitly selected files locally. Optional engines execute on your device.</p>')+section('What can still reach a network','<p>GitHub serves this website, source and downloads and has its own logging/privacy practices. Browser/OS updates and third-party optional tools have separate behavior. Cloud-backed file pickers and synced save locations can upload outside Prepare’s control. Choose local, non-synced storage.</p>')+section('Receipts and support','<p>Receipts expose hashes, sizes and personal requirements; browser receipts may include filenames. They are optional and saved locally. Do not post private documents, passwords or sensitive receipt data in public issues. There is no telemetry opt-out because no telemetry is built in.</p>'))
add('security','Useful defenses.<br>Honest limits.','Prepare is not a sanitizer, malware scanner, full parser sandbox or authenticity service.',section('Threat boundaries','<p>Input limits, private staging, exclusive output publication and subprocess boundaries reduce specific risks. Native parsers still process untrusted bytes. Browser workers improve responsiveness, not universal containment. Avoid hostile files and keep your OS, browser and optional engines updated.</p><p>Encryption protects a PDF according to the selected operation; it does not secure all temporary storage. Rewriting can invalidate signatures or lose features. Review the output.</p>')+section('Report privately',f'<p>{link(REPO+"/security/advisories/new","Open a private security advisory →")}</p><p>Include a minimal synthetic reproduction and version, not unrelated private files. No guaranteed response time or bounty is promised.</p>'))
add('terms','Use the right tool.<br>Keep responsibility visible.','Software is provided without warranty under its applicable license.',section('Your documents','<p>You retain your files. Ensure you have permission to process them. Keep originals, inspect outputs and confirm the destination’s current requirements. Prepare does not guarantee application acceptance, legal validity, accessibility conformance or signature preservation.</p>')+section('Licenses and third parties','<p>Current project-owned code uses Apache-2.0. Third-party components have separate terms. Older distributed artifacts retain their original license; see <a href="/licensing/">the version boundary</a>. Hosted services and optional engines have their own terms. This page is not legal advice.</p>'))
add('accessibility','Built for more than<br>a mouse and perfect vision.','Semantic pages, visible focus, keyboard controls, reduced motion and explicit unknown states.',section('What is tested','<p>Responsive overflow, keyboard skip links, labeled inputs, light/dark modes and no-JavaScript navigation are automated checks. The PDF workspace exposes reordering as labeled buttons rather than drag-only controls.</p>')+section('What is not claimed','<p>No blanket WCAG certification or complete screen-reader qualification. A prepared PDF is not automatically accessible. Desktop screen-reader behavior depends on OS/Tk and needs broader user testing. Report a reproducible barrier through <a href="/contact/">support</a>.</p>'))
add('faq','Straight answers.','The important boundaries of local preparation and verification, in one place.', ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in [
('Can it make any file smaller than any limit?','No. Lossless optimization may increase size; lossy rasterization changes fidelity. A requirement is a gate, not a compression promise.'),('Does a passed check mean the portal will accept my file?','No. Checks apply only to the observed facts and rules you supplied. Portal acceptance and visual review remain separate.'),('Does anything upload my documents?','Prepare processing does not. Hosting requests, browser/OS behavior and cloud-synced storage are separate boundaries.'),('Is it open source?','Current project-owned code is Apache-2.0. Dependencies retain their own licenses. Historical releases through 0.8 remain Hippocratic 3.0.'),('Where are the browser store listings?','Not published. Developer-mode packages and temporary Firefox installation are not marketplace distribution.'),('Does it preserve signatures and Office layout?','Do not assume either. Rewritten PDFs can invalidate signatures; Office conversion is text-first, not layout-faithful.')]))
add('about','A product with<br>a narrower promise.','Prepare exists to close the gap between having a file and having the right copy.',section('By Goni Sulaiman','<p>I am building Prepare around local preparation and honest verification. I want the tool to tell you what it knows, what it changed and what still needs your judgment—not distract you with a feature count.</p>')+section('Keep the name; sharpen the meaning','<p>Prepare is descriptive and not exclusive. No trademark clearance, domain ownership beyond established hosting, or global naming uniqueness is claimed. Existing download URLs and user paths are preserved instead of being migrated for aesthetics.</p>'))
add('community','Build in the open.<br>Keep private files private.','Useful reports, explicit trade-offs and reproducible evidence.',section('Join the work',f'<p>{link(REPO+"/issues","Issues and feature requests →")} · <a href="/contributing/">Contributing</a> · <a href="/roadmap/">Product direction</a></p><p>Share the requirement and smallest synthetic reproduction. Do not upload a real passport, application or confidential document just to demonstrate a bug.</p>'))
add('contributing','Show the failing case.','Contributions should improve a user workflow and include evidence.',section('A practical contribution','<ol><li>Describe the requirement or failure, not just a proposed feature.</li><li>Create a synthetic fixture and regression test.</li><li>Preserve originals, limits and honest unknown states.</li><li>Run relevant tests and document adapter/platform limits.</li><li>Preserve third-party notices and identify copied code.</li></ol><p>New contributions to project-owned code are under Apache-2.0. No assumption is made that vendor code can be relicensed.</p>')+section('Development',f'<p>{link(REPO+"/blob/main/CONTRIBUTING.md","Contribution guide →")} · {link(REPO+"/blob/main/GOVERNANCE.md","Governance →")} · {link(REPO+"/blob/main/CODE_OF_CONDUCT.md","Code of conduct →")}</p>'))
add('licensing','More freedom.<br>Attribution intact.','Apache-2.0 for current project-owned source; a clear boundary for everything else.',section('Why Apache-2.0','<p>A permissive license with an explicit patent grant and patent-termination terms supports commercial integration, forks, SDKs and plugins without a use-policy license restriction. This is an engineering/ecosystem choice, not legal certainty.</p>')+section('Not a retroactive rewrite','<p>Historical releases through 0.8.0-beta.1 keep the Hippocratic License 3.0 under which they were distributed. New source and future artifacts identify their own license. Vendor code remains under its upstream MIT/BSD/Apache/zlib or other applicable terms.</p>')+section('Provenance',f'<p>{link(REPO+"/blob/main/docs/LICENSING.md","Audit and transition rationale →")} · {link(REPO+"/blob/main/NOTICE","NOTICE →")} · {link(REPO+"/blob/main/docs/DEPENDENCIES.md","Dependency licenses →")}</p>'))
add('roadmap','A preparation layer.<br>Not a feature collection.','Prioritize repeatable local workflows, requirement gates and evidence over universal conversion claims.',section('Current direction','<p>The 0.9 generation joins desktop, CLI and browser workflows through personal requirements and receipts. The extension is intentionally a dedicated preparation tab, not a privileged upload interceptor.</p>')+section('Next decisions need evidence','<p>Batch submission bundles, workflow replay and loss comparison are candidates—not shipped promises. Native mobile expansion and store distribution need platform qualification and maintainer account steps. No release dates, automatic acceptance or all-format roadmap is promised.</p><p><a href="https://github.com/gonisulaimann/Prepare/blob/main/docs/PRODUCT-DECISION-09.md">Research and prioritization →</a></p>'))
add('changelog','Changes with a boundary.','New behavior is versioned; historical release claims stay historical.',section('0.9 workspace generation','<p>Personal requirement gates on desktop output, shared-worker CLI, hash-bound receipts and saved-copy verification. Local PDF extension adapters. Rebuilt product site and workspace identity. Prospective Apache-2.0 licensing with third-party notices preserved.</p>')+section('0.8 and earlier','<p>0.8 introduced the broader desktop suite. 0.7 added browser/Node PDF workflows. Stable 0.5 image tools and experimental Android remain downloadable with their original scope.</p><p><a href="/releases/">Exact published versions →</a></p>'))
add('releases','Artifacts, not adjectives.','GitHub releases are the authority for what is publicly downloadable.',section('Published release record',f'<p>{link(REPO+"/releases","Open all releases →","button")}</p><p>Beta is not stable. Store packages are not store listings. Each release describes tests, platform qualification, checksums and limitations. Current development version: {esc(PRODUCT["version"])} ({esc(PRODUCT["releaseStatus"])}).</p>')+section('Preserved historical versions',f'<p>{link(REPO+"/releases/tag/v0.8.0-beta.1","0.8 desktop beta")} · {link(REPO+"/releases/tag/v0.7.0-beta.1","0.7 PDF workbench")} · {link(REPO+"/releases/tag/v0.5.0","0.5 stable image tools")}</p>'))
add('contact','A useful report<br>starts with a safe example.','Public bugs and feature requests belong on GitHub. Security reports have a private channel.',section('Support',f'<p>{link(REPO+"/issues/new/choose","Open an issue →","button")}</p><p>Include version, OS/browser, expected result and a small synthetic fixture. No support SLA or private email inbox is promised. Do not include secrets or personal documents.</p>')+section('Security',f'<p>{link(REPO+"/security/advisories/new","Private vulnerability report →")}</p>'))

inventory=json.loads((ROOT/'downloads.json').read_text())
downloads='<p id="platform-note" role="status">Choose your platform. Every download remains available without JavaScript.</p><div class="platform-choices">'+''.join(f'<button type="button" data-platform="{p}" aria-pressed="false">{label}</button>' for p,label in [('all','All'),('mac','macOS'),('windows','Windows'),('linux','Linux'),('browser','Browser'),('android','Android')])+'</div><div class="download-list">'
for item in inventory:
    downloads+=f'<article data-download="{esc(item["platform"])}"><div><p class="eyebrow">{esc(item["channel"])} / {esc(item["version"])}</p><h2>{esc(item["label"])}</h2><p>{esc(item["notes"])}</p><p class="fine">{esc(item["architecture"])} · {item["bytes"]:,} bytes · {esc(item["license"])}</p></div><div><a class="button" href="{esc(item["url"])}">Download ZIP ↓</a><details><summary>SHA-256 checksum</summary><code class="checksum">{esc(item["sha256"])}</code></details></div></article>'
downloads+='</div><script src="/platform.js" defer></script>'
downloads+=section('Before opening','<p>Verify the checksum, extract the entire package and read its README. Desktop binaries are unsigned/not notarized. Do not bypass operating-system protections. Browser extensions are developer-mode/temporary-install previews, not store-published products. Older downloads carry historical licenses and narrower capabilities.</p><p><a href="/requirements/">Requirements</a> · <a href="/extension/">Extension installation</a> · <a href="/mobile/">Android status</a></p>')
add('download','The right tool.<br>The right download.','Version, architecture, size and checksum—before you commit your bandwidth.',downloads)
for slug,(title,deck,body) in pages.items():
    out=ROOT/slug/'index.html';out.parent.mkdir(exist_ok=True);out.write_text(shell(title,deck,body,slug+'/'))
(ROOT/'404.html').write_text(shell('This page is not here.','The file may have moved. Your documents have not.',section('Find your way back','<p><a href="/">Home</a> · <a href="/download/">Downloads</a> · <a href="/documentation/">Documentation</a></p>'),'404.html').replace('<head>','<head><meta name="robots" content="noindex">'))
print('Generated home,',len(pages),'purposeful product pages and 404')
